version: '3.5'
services:
  db:
    image: postgres:9.6.2-alpine
    container_name: iiko-db
    environment:
      POSTGRES_DB: iiko-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      TZ: "Asia/Tokyo"
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: always
    command: ["-d", "iiko-db"]
    ports:
      - 5432:5432
    networks:
      - iiko

  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@linuxhint.com
      PGADMIN_DEFAULT_PASSWORD: 12345678
      PGADMIN_LISTEN_PORT: 80
    ports:
    - 8080:80
    depends_on:
      - db
    volumes:
    - pgadmin-data:/var/lib/pgadmin
    links:
    - "db:pgsql-server"
    networks:
      - iiko

networks:
  iiko:

volumes:
  pg-data:
  pgadmin-data:
  